use flags from the build system (rpm/debian)

diff --git a/ezmlm-idx-7.2.2/create_rpm b/ezmlm-idx-7.2.2/create_rpm
--- a/ezmlm-idx-7.2.2/create_rpm
+++ b/ezmlm-idx-7.2.2/create_rpm
@@ -1,4 +1,34 @@
 #!/bin/sh
+version=$(cat conf-version)
+
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
+
 if test -f $HOME/.rpmmacros
 then
 	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
@@ -11,7 +41,7 @@ then
 else
 	rpmbuild=$HOME/rpmbuild
 fi
-version=$(cat conf-version)
+
 copy_src=0
 echo -n "Copy Source Files - "
 read key
@@ -90,28 +120,38 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 	else
 		cp ezmlm-idx-$version/ezmlm-idx.spec /tmp
 	fi
-	rpmbuild -ba --clean /tmp/ezmlm-idx.spec
-	/bin/rm -f /tmp/ezmlm-idx.spec
-	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	for i in ezmlm-idx ezmlm-idx-cgi ezmlm-idx-mysql ezmlm-idx-sqlite3 ezmlm-idx-pgsql
-	do
-		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
-	done
-	rpm --addsign $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
-	echo -n "RPM lint for ezmlm-idx-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/ezmlm-idx.spec"
+		rpmbuild -ba --clean --quiet /tmp/ezmlm-idx.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/ezmlm-idx.spec"
+		rpmbuild -ba --clean /tmp/ezmlm-idx.spec
+	fi
+	if [ $? -eq 0 ] ; then
+		/bin/rm -f /tmp/ezmlm-idx.spec
+		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
 		for i in ezmlm-idx ezmlm-idx-cgi ezmlm-idx-mysql ezmlm-idx-sqlite3 ezmlm-idx-pgsql
 		do
-			echo $i
-			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
-			echo ------------------------
+			rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
 		done
-		echo ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+		rpm --addsign $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
+		echo -n "RPM lint for ezmlm-idx-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			for i in ezmlm-idx ezmlm-idx-cgi ezmlm-idx-mysql ezmlm-idx-sqlite3 ezmlm-idx-pgsql
+			do
+				echo $i
+				rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
+				echo ------------------------
+			done
+			echo ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm -f /tmp/ezmlm-idx.spec
 	fi
 fi
 if [ $copy_src -eq 1 ] ; then
